### ISSUE TITLE
In python

### ISSUE THREAD

**Issue by sabas1080** [fabe/spectacles-cli#1]
Hi @fabe 

I'm trying to do something similar in python, do you have any suggestions how to get started?
 
Or the command in FFMpeg to make it direct in terminal?

Thanks

**Comment by sabas1080** [comment]
In terminal, would it be something like that?

`ffmpeg -i video.mp4 -i overlay.png -map 0:a -filter_complex "scale=-2:720[rescaled] crop=ih:ih:iw/4:0 overlay=main_w-overlay_w)/2:main_h-overlay_h)/2"  `

**Comment by fabe** [comment]
Hey @sabas1080, almost—the chaining isn't quite right:

    ffmpeg -i video.mp4 -i overlay.png -map 0:a -filter_complex "scale=-2:720[rescaled];[rescaled]crop=ih:ih:iw/4:0[crop];[crop]overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2" output.mp4

Good luck! Let me know if you have other questions. 🙌
